# Prometheus Configuration
# Scrapes metrics from Docker containers and system

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'file-storage-app'
    environment: 'production'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Node Exporter - System metrics (CPU, Memory, Disk, Network)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'system'
          instance: 'ec2-file-storage'

  # cAdvisor - Container metrics (Docker containers)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'containers'
